version: '3.8'

services:
  mongo-repl1:
    container_name: mongo-repl1
    image: mongo:latest
    volumes:
      - ./mongos/data1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    ports:
      - 3000:3000
    links:
      - mongo-repl2
      - mongo-repl3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "unitTest", "--port", "3000" ]
  mongo-repl2:
    container_name: mongo-repl2
    image: mongo:latest
    volumes:
      - ./mongos/data2:/data/db
    networks:
      - mongors-network
    ports:
      - 3001:3001
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "unitTest", "--port", "3001" ]
  mongo-repl3:
    container_name: mongo-repl3
    image: mongo:latest
    volumes:
      - ./mongos/data3:/data/db
    networks:
      - mongors-network
    ports:
      - 3002:3002
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "unitTest", "--port", "3002" ]

networks:
  mongors-network:
    driver: bridge