version: "3.8"

services:
  mongo-repl1:
    container_name: mongo-repl1
    image: mongo:latest
    volumes:
      - ./mongos/data1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    ports:
      - 3300:3300
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "${REPLICA_SET_NAME}",
        "--port",
        "3300",
      ]
  mongo-repl2:
    container_name: mongo-repl2
    image: mongo:latest
    volumes:
      - ./mongos/data2:/data/db
    networks:
      - mongors-network
    ports:
      - 3301:3301
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "${REPLICA_SET_NAME}",
        "--port",
        "3301",
      ]
  mongo-repl3:
    container_name: mongo-repl3
    image: mongo:latest
    volumes:
      - ./mongos/data3:/data/db
    networks:
      - mongors-network
    ports:
      - 3302:3302
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "${REPLICA_SET_NAME}",
        "--port",
        "3302",
      ]

networks:
  mongors-network:
    driver: bridge
